#!/bin/bash

# mc = make code
ROOTNATIVELIBS=~/bin/clean/lib
ARGENVLIB=$CHIDEHOME/bin/clean/lib/ArgEnv
LIBS=$ROOTNATIVELIBS/Gast/:$ROOTNATIVELIBS/Generics:$ROOTNATIVELIBS/StdLib:$JN/CleanLibs/GenericByCG:$JN/CleanLibs:$ROOTNATIVELIBS/MersenneTwister:$JN/CleanLibs/gastTCP/:$ROOTNATIVELIBS/../libsFromClean2.3Windows/Gast/:$ARGENVLIB
# <&y2011.11.15.18:41:13& I noticed that leaving out the -l switch also works. But just following the README of the ArgEnv lib...>
clm -l $ARGENVLIB/ArgEnvC.o -I $LIBS adGen
mv a.out adGen
